name: roomies
description: A roommate management application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  uuid: ^4.4.2
  intl: ^0.20.2
  firebase_storage: 13.0.4
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter # Ta nazwa musi być IDENTYCZNA jak w constants.dart
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf # Tu musi być dokładna nazwa pliku który wrzuciłaś

    - family: StackSansNotch
      fonts:
        - asset: assets/fonts/StackSansNotch-VariableFont_wght.ttf

  assets:
   - assets/images/logo_roomies.png
